# TODO: https://github.com/leanflutter/flutter_distributor/issues/25
appName: Clash Pro For Flutter
appId: D7A38B8F-24E5-46F5-B6FB-B2DC03EE943D
appPublisher: csj8520
appPublisherUrl: https://github.com/csj8520/clash_pro_for_flutter
