app_id: D7A38B8F-24E5-46F5-B6FB-B2DC03EE943D
publisher_name: csj8520
publisher_url: https://github.com/csj8520/clash_for_flutter
display_name: Clash For Flutter
create_desktop_icon: true
install_dir_name: Clash For Flutter
