# TODO: https://github.com/leanflutter/flutter_distributor/issues/25
publisher_name: Clash For Flutter
display_name: Clash For Flutter
install_dir_name: Clash For Flutter
appId: D7A38B8F-24E5-46F5-B6FB-B2DC03EE943D
appPublisher: csj8520
appPublisherUrl: https://github.com/csj8520/clash_for_flutter
